spring:
  application:
    name: report-service
  main:
    banner-mode: off
  profiles:
    active: dev
  datasource:
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      continue-on-error: true
server:
  port: 8090

