spring:
  application:
    name: gateway-service
  main:
    banner-mode: off
    web-application-type: reactive

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

#spring:
 # application:
  #  name: gateway
  #cloud:
  #  gateway:
  #    routes:
  #      - id: currency-conversion-service
  #        #uri: http://localhost:9100/
  #        uri: lb://currency-conversion-service/
  #        predicates:
  #          - Path=/cc-converter/**
  #        filters:
  #          - RewritePath=/cc-converter/from/(?<from>.*)/to/(?<to>.*)/quantity/(?<quantity>.*), /currency-converter/from/$\{from}/to/$\{to}/quantity/$\{quantity}
  #      - id: forex-service
          #uri: http://localhost:9000/, http://localhost:9001/
  #        uri: lb://forex-service/
  #        predicates:
  #          - Path=/fx-exchange/**
  #        filters:
  #          - RewritePath=/fx-exchange/from/(?<from>.*)/to/(?<to>.*), /forex-exchange/from/$\{from}/to/$\{to}
  #    discovery:
  #      locator:
  #        enabled: true
  #        lower-case-service-id: true