eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #register-with-eureka: false
      defaultZone: http://localhost:8761/eureka/

login:
  url: http://localhost:8083

patient:
  header:
    key: DevKey
    value: DevValue
  rest:
    url: http://PATIENT-SERVICE/
    urlLocal: http://localhost:8084/

doctor:
  header:
    key: DevKey
    value: DevValue
  rest:
    url: http://DOCTOR-SERVICE/
    urlLocal: http://localhost:8085/

emp:
  rest:
    url: https://dummy.restapiexample.com/api/v1/
    header:
      key: DevKey
      value: DevValue