eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #register-with-eureka: false
      defaultZone: http://localhost:8761/eureka/

login:
  url: http://localhost:8085