eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #register-with-eureka: false
      defaultZone: http://localhost:8761/eureka/

login:
  rest:
    url: http://LOGIN-SERVICE/
    localUrl: http://localhost:8082

jwt:
  enabled: true