eureka:
  instance:
    prefer-ip-address: true
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
login:
  rest:
    url: http://LOGIN-SERVICE/
    localUrl: http://localhost:8082

patient:
  service:
    url: http://PATIENT-SERVICE/


jwt:
  enabled: true